version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: esig_db
    environment:
      - POSTGRES_DB=esig_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - esig-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  esig-postgres: